### ISSUE TITLE
Hypermedia generation should be a little closer to a faux spec

### ISSUE THREAD

**Issue by avoidwork** [avoidwork/tenso#43]
I'm not saying implement JSON-API or JSON-HAL (shutter), but `link` should be `links`, and there's probably one or two other minor tweaks that can be made.

**Comment by avoidwork** [comment]
The new proposed shape would be:

```json
{
  "data": "null or payload",
  "error": "null or message",
  "links": ["currently embedded in `data` with pre-2.0.0"],
  "status": 0
}
```

This could be the beginning of an RFC.

**Comment by AlexZeitler** [comment]
Ever considered UBER-Hypermedia?
https://rawgit.com/uber-hypermedia/specification/master/uber-hypermedia.html

**Comment by avoidwork** [comment]
I hadn't, but I shall now.
