### ISSUE TITLE
lws deprecated

### ISSUE THREAD

**Issue by alexhultman** [avoidwork/tenso#63]
Hi,

I would like to unpublish lws from NPM but cannot do so because of the dependeny Tenso has. lws is no longer supported and has been deprecated for 3 months now. It will not continue to work with newer Node.js versions and will not be updated. If you want high perf WebSockets you could check out uws instead, this module also supports SSL which lws does not.

**Comment by avoidwork** [comment]
Sure, been on my 'to do' list for a while due to that deprecation message. Can you hold off until the weekend?

**Comment by alexhultman** [comment]
Ofc, there is no rush.
