### ISSUE TITLE
Custom Caching Strategy

### ISSUE THREAD

**Issue by ameykshirsagar** [avoidwork/tenso#68]
Hi,
I am interested in implementing a custom response caching strategy using [multilevel](https://github.com/juliangruber/multilevel) for better caching that has inbuilt compression. How can I override the inbuilt caching mechanism, if I want to??

Thanks

**Comment by avoidwork** [comment]
Hi,

The README is out of date; the old cache mechanism has been removed from the underlying server, so at this point there's only an etag header middleware. I don't think this project is compatible with multilevel; this is a gateway that handles serialization, hypermedia & common things like pagination, while multilevel is  meant to run as a server.

**Comment by ameykshirsagar** [comment]
Yeah. It's true that multilevel won't work here directly but if I have to deploy multiple instances using load balancer then I shall need a common cache across the instances. Anyway if I can get a mechanism to set and get an etag as an example, then that would be great as well. I can figure out the rest as well.

**Comment by avoidwork** [comment]
I'll have to think about this; it'd be in this project https://github.com/avoidwork/tiny-etag

**Comment by avoidwork** [comment]
I could add events / 'on*' handlers that could be overridden for a custom strategy, so local state could propagate to whatever you want.

**Comment by ameykshirsagar** [comment]
Ok. I will try that and get back to you. Thanks for your help though

**Comment by avoidwork** [comment]
Hi,

I've started making changes to support this; it'll be ready in a day two. I'll setup code such that an `onchange()` function will receive a serialized copy of cache (tiny-lru), for broadcast/propagation as you see fit.

**Comment by ameykshirsagar** [comment]
That will be great. I was looking for the same. Perhaps I can come up with a tutorial for creating an API gateway with actual microservices tied up in a complete ecosystem of API stack using tenso.
Appreciate the efforts.

**Comment by avoidwork** [comment]
Hi,

See https://github.com/avoidwork/turtle.io#etags for how to enable this by config. A cache `set()` will not trigger a notification of the preceding `remove()`, so there won't be unwanted "chatter".

**Comment by avoidwork** [comment]
I updated this project's README as well: https://github.com/avoidwork/tenso#etags
