### ISSUE TITLE
express-session memory leak

### ISSUE THREAD

**Issue by roccomuso** [avoidwork/tenso#96]
The default "memory" storage for sessions suffer a well known memory leak. As pointed out on the `express-session` documentation. The usage is discouraged in production.

Consider switching to a leak-proof in-memory store: [memorystore](https://github.com/roccomuso/memorystore)

**Comment by avoidwork** [comment]
I suggest you use redis instead of keeping the session in this app; that's intentional from my pov.

**Comment by avoidwork** [comment]
to explain, the in memory store is meant for dev... i'd never recommend running in prod with your session data inside of the tenso instance (only); for prod deploys i always have redis holding the session data.
